language:
  - swift
osx_image: xcode10.1

install: gem install cocoapods xcpretty fastlane --pre
podfile: Podfile
xcode_destination: platform=macos

make test lint

notifications:
email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
