language:
  - swift
osx_image: xcode10.1

install: gem install cocoapods xcpretty fastlane --pre
podfile: Podfile

xcode_destination: platform=macos

- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Ansi/${POD_NAME}.xcworkspace -scheme ${POD_NAME} -sdk | xcpretty
- pod lib lint

notifications:
email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
