language:
  - swift
osx_image: xcode10.1

install: gem install cocoapods xcpretty fastlane --pre
xcode_workspace: Ansi.xcworkspace
xcode_scheme: Ansi
xcode_destination: platform=macOS

notifications:
email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
