language:
  - swift
osx_image: xcode10.1

xcode_project: Ansi.xcodeproj
xcode_scheme: Ansi
xcode_destination: platform=macos

notifications:
email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
